### ISSUE TITLE
Only change to "params" screen when the mode is selected

### ISSUE THREAD

**Issue by crisconru** [Respyrator/gui#3]
You only can change to the next screen, **PARAM SCREEN**, if you selected one mode. The tabs don't work already
<hr>
Update:
At the MODES SCREEN you should only switch of screen when one mode is selected. So PARAMS and ALARMS tabs don't work, only modes buttons work.

**Comment by JJ** [comment]
Hey, hey, hey, stop here, buster. First, create a milestone to express the MVP you want to have at the end of this cycle. Then, issues with some kind of priority...

**Comment by crisconru** [comment]
You're right @JJ sorry. As Simpsons said "es mi primerito día" (with this).
Could the milestones be one for each screen with all its basic functionality?

**Comment by JJ** [comment]
A milestone is a minimal viable product. Screens (and/or its behavior) can be one of them. When a milestone is reached, the state of the project has changed and what it describes is viable by itself.
